In [1]:
import pandas as pd
import numpy as np
from common.bio.constants import *

In [2]:
DIR_PATH= "C:\\Users\\Donatas\\Workspace\\Machine Learning\\SynBioAi\\PREnzyme\\data\\amino_acid\\"

In [455]:
props = pd.read_csv(DIR_PATH+'Physicochemical_props1.txt', sep=" ", header=0, index_col=0).transpose()
aadata = pd.read_csv(DIR_PATH+'aadata.txt', sep=",", header=0, index_col=0)
pi_values = pd.read_csv(DIR_PATH+'pk_pi_values.txt', sep=",", header=0)
generated = pd.read_csv(DIR_PATH+'generated_embeddings_8.txt', sep=",", header=None, index_col=0)

In [456]:
props.shape

(20, 8)

In [457]:
data = pd.merge(left=props, right=aadata[["3-letter","AminoAcid", "Residue mass"]], how="inner", left_index=True, right_index=True)

In [458]:
data.shape

(20, 11)

In [459]:
data = pd.merge(left=data.reset_index(), right=pi_values[["AminoAcid", "pI"]], how="inner", on= "AminoAcid", left_index=True).set_index('index')

In [460]:
data.shape

(20, 12)

Drop non numeric columns 

In [462]:
data = data.drop(["3-letter", "AminoAcid"], axis =1 )
data = data.drop(["Pc", "Residue mass"], axis =1 )

In [463]:
#data = data.drop(["3-letter", "AminoAcid", "Chou-Fasman code for helix propensity","Chou-Fasman code for sheet propensity"], axis=1)

In [464]:
data.abs().max(axis=0)

Lip      1.4600
Hyd      1.4797
S_H    133.6980
S_L     42.7610
Pa       1.5100
Pb       1.7000
Vol    227.8000
pI      10.7600
dtype: float64

In [465]:
std = data.std(ddof=0, axis=0)

In [466]:
std

Lip     0.430752
Hyd     0.402264
S_H    30.863267
S_L    12.526324
Pa      0.273971
Pb      0.358961
Vol    39.937094
pI      1.724522
dtype: float64

In [467]:
data_std = data.div(std, axis=1)

In [468]:
data_std

Lip       Hyd       S_H       S_L        Pa        Pb       Vol  \
index                                                                         
A      0.404874  0.000000  1.126776  0.000000  5.183034  2.312231  2.218489   
R      2.884260 -3.678430  2.942041  2.818864  3.577024  2.590813  4.341828   
N      1.484846 -1.792604  1.636509  1.419411  2.445516  2.479380  2.947135   
D      1.406378 -2.311418  1.212347  2.017615  3.686524  1.504343  2.781875   
C      0.575505 -0.597120  0.763237  2.431200  2.555017  3.315127  2.716773   
Q      2.329880 -1.792604  2.270920  1.426276  4.051527  3.064403  3.603166   
E      2.394650 -2.311418  1.851982  2.041541  5.511536  1.030754  3.465450   
G      0.048288  0.000000  0.121892  0.000000  2.080514  2.089365  1.504867   
H      1.886005 -1.930573  2.662388  1.106709  3.650024  2.423664  3.836033   
I      2.564354  0.000000  2.870921  0.000000  3.942026  4.457313  4.174064   
L      2.996157  0.000000  2.739438  0.000000  4.416529  3.621567  4.174064   
K      3.389423 -1.548486  3.166029  0.644962  4.234028  2.061507  4.224143   
M      2.499815 -0.762683  2.279833  1.854495  5.292535  2.925112  4.078915   
F      1.024256 -0.297069  3.424945  0.897869  4.124527  3.844433  4.754978   
P      0.748923  0.000000  2.243120  0.000000  2.080514  1.532201  3.072332   
S      0.544629 -1.501502  0.844629  1.274197  2.810518  2.089365  2.228505   
T      3.311652 -1.086103  1.514065  1.281222  3.029520  3.315127  2.907072   
W      1.941721 -1.071436  4.331946  1.188058  3.942026  3.816574  5.703970   
Y      1.052578 -1.465704  2.623345  3.413691  2.518517  4.095156  4.847624   
V      1.235979  0.000000  2.521152  0.000000  3.869025  4.735895  3.505513   

             pI  
index            
A      3.479226  
R      6.239412  
N      3.137102  
D      1.606243  
C      2.939946  
Q      3.276271  
E      1.867184  
G      3.461830  
H      4.401221  
I      3.490823  
L      3.467628  
K      5.647943  
M      3.328459  
F      3.177693  
P      3.653187  
S      3.293667  
T      3.247277  
W      3.415440  
Y      3.282070  
V      3.456031

In [469]:
data_std["Hyd"] = data_std["Hyd"] * (-1)
transposed = data_std.transpose()
transposed["0"] = [0, 0, 0, 0, 0, 0, 0, 7/1.724522]
data_std = transposed.transpose()
#data = pd.merge(left=data, right=generated, how="inner", left_index=True, right_index=True)

In [470]:
data_std.sort_index()

Lip       Hyd       S_H       S_L        Pa        Pb       Vol  \
index                                                                         
0      0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
A      0.404874 -0.000000  1.126776  0.000000  5.183034  2.312231  2.218489   
C      0.575505  0.597120  0.763237  2.431200  2.555017  3.315127  2.716773   
D      1.406378  2.311418  1.212347  2.017615  3.686524  1.504343  2.781875   
E      2.394650  2.311418  1.851982  2.041541  5.511536  1.030754  3.465450   
F      1.024256  0.297069  3.424945  0.897869  4.124527  3.844433  4.754978   
G      0.048288 -0.000000  0.121892  0.000000  2.080514  2.089365  1.504867   
H      1.886005  1.930573  2.662388  1.106709  3.650024  2.423664  3.836033   
I      2.564354 -0.000000  2.870921  0.000000  3.942026  4.457313  4.174064   
K      3.389423  1.548486  3.166029  0.644962  4.234028  2.061507  4.224143   
L      2.996157 -0.000000  2.739438  0.000000  4.416529  3.621567  4.174064   
M      2.499815  0.762683  2.279833  1.854495  5.292535  2.925112  4.078915   
N      1.484846  1.792604  1.636509  1.419411  2.445516  2.479380  2.947135   
P      0.748923 -0.000000  2.243120  0.000000  2.080514  1.532201  3.072332   
Q      2.329880  1.792604  2.270920  1.426276  4.051527  3.064403  3.603166   
R      2.884260  3.678430  2.942041  2.818864  3.577024  2.590813  4.341828   
S      0.544629  1.501502  0.844629  1.274197  2.810518  2.089365  2.228505   
T      3.311652  1.086103  1.514065  1.281222  3.029520  3.315127  2.907072   
V      1.235979 -0.000000  2.521152  0.000000  3.869025  4.735895  3.505513   
W      1.941721  1.071436  4.331946  1.188058  3.942026  3.816574  5.703970   
Y      1.052578  1.465704  2.623345  3.413691  2.518517  4.095156  4.847624   

             pI  
index            
0      4.059096  
A      3.479226  
C      2.939946  
D      1.606243  
E      1.867184  
F      3.177693  
G      3.461830  
H      4.401221  
I      3.490823  
K      5.647943  
L      3.467628  
M      3.328459  
N      3.137102  
P      3.653187  
Q      3.276271  
R      6.239412  
S      3.293667  
T      3.247277  
V      3.456031  
W      3.415440  
Y      3.282070

In [471]:
data = data_std

In [472]:
delta_0_center = (data.max(axis=0)+data.min(axis=0))/2 - np.abs(np.random.normal(scale=0.0001, size=data.shape[1]))
data = (data.subtract(delta_0_center, axis=1))#.div(data.std(ddof=0, axis=0), axis=1))
# data = (data.subtract(data.mean(axis=0), axis=1).div(data.std(ddof=0, axis=0), axis=1))
data = data.div(data.abs().max(axis=0)+np.abs(np.random.normal(scale=0.04, size=data.shape[1])), axis=1)

In [473]:
data = data + np.random.normal(scale=0.0001, size=data.shape)

In [474]:
data.max(), data.min()

(Lip    0.991150
 Hyd    0.990637
 S_H    0.974184
 S_L    0.975732
 Pa     0.984371
 Pb     0.986957
 Vol    0.994519
 pI     0.992312
 dtype: float64, Lip   -0.990868
 Hyd   -0.990640
 S_H   -0.973756
 S_L   -0.975707
 Pa    -0.983967
 Pb    -0.986952
 Vol   -0.994721
 pI    -0.992262
 dtype: float64)

In [475]:
data

Lip       Hyd       S_H       S_L        Pa        Pb       Vol  \
index                                                                         
A     -0.754024 -0.990640 -0.467359 -0.975707  0.867070 -0.023168 -0.220794   
R      0.695588  0.990637  0.349144  0.635851  0.293391  0.092642  0.519654   
N     -0.122615 -0.025162 -0.238010 -0.164102 -0.110572  0.046628  0.033141   
D     -0.168480  0.254397 -0.428693  0.177709  0.332541 -0.359855 -0.024478   
C     -0.654440 -0.668911 -0.630732  0.414226 -0.071636  0.394790 -0.047221   
Q      0.371546 -0.025078  0.047388 -0.160138  0.462685  0.290440  0.262060   
E      0.409223  0.254446 -0.141095  0.191413  0.984371 -0.557454  0.214064   
G     -0.962751 -0.990590 -0.919051 -0.975304 -0.241084 -0.116098 -0.469822   
H      0.111706  0.049277  0.223331 -0.343035  0.319229  0.023263  0.343287   
I      0.508630 -0.990626  0.317163 -0.975620  0.423664  0.871074  0.461265   
L      0.761047 -0.990352  0.257948 -0.975536  0.593312  0.522599  0.460908   
K      0.991150 -0.156517  0.449906 -0.606928  0.528167 -0.127749  0.478488   
M      0.470856 -0.579747  0.051103  0.084377  0.906042  0.232290  0.428022   
F     -0.391900 -0.830540  0.566276 -0.462288  0.488775  0.615523  0.663587   
P     -0.552991 -0.990519  0.034687 -0.975412 -0.241247 -0.348413  0.076876   
S     -0.672513 -0.181890 -0.594038 -0.247199  0.019557 -0.116193 -0.217411   
T      0.945609 -0.405530 -0.293115 -0.243042  0.097942  0.394727  0.019238   
W      0.144605 -0.413660  0.974184 -0.296443  0.423797  0.603931  0.994519   
Y     -0.375230 -0.201153  0.205606  0.975732 -0.084933  0.720015  0.696000   
V     -0.268057 -0.990309  0.159775 -0.975643  0.397758  0.986957  0.227810   
0     -0.990868 -0.990493 -0.973756 -0.975496 -0.983967 -0.986952 -0.994721   

             pI  
index            
A     -0.190182  
R      0.992312  
N     -0.336553  
D     -0.992262  
C     -0.421094  
Q     -0.276944  
E     -0.880627  
G     -0.197489  
H      0.204822  
I     -0.185155  
L     -0.195070  
K      0.739140  
M     -0.254631  
F     -0.319135  
P     -0.115677  
S     -0.269544  
T     -0.289246  
W     -0.217299  
Y     -0.274526  
V     -0.200038  
0      0.058469

In [476]:
# transposed = data.transpose()
# transposed[0] = -1 + np.abs(np.random.normal(scale=0.001, size=data.shape[1]))
# final = transposed.transpose()
final=data.sort_index()

In [477]:
final

Lip       Hyd       S_H       S_L        Pa        Pb       Vol  \
index                                                                         
0     -0.990868 -0.990493 -0.973756 -0.975496 -0.983967 -0.986952 -0.994721   
A     -0.754024 -0.990640 -0.467359 -0.975707  0.867070 -0.023168 -0.220794   
C     -0.654440 -0.668911 -0.630732  0.414226 -0.071636  0.394790 -0.047221   
D     -0.168480  0.254397 -0.428693  0.177709  0.332541 -0.359855 -0.024478   
E      0.409223  0.254446 -0.141095  0.191413  0.984371 -0.557454  0.214064   
F     -0.391900 -0.830540  0.566276 -0.462288  0.488775  0.615523  0.663587   
G     -0.962751 -0.990590 -0.919051 -0.975304 -0.241084 -0.116098 -0.469822   
H      0.111706  0.049277  0.223331 -0.343035  0.319229  0.023263  0.343287   
I      0.508630 -0.990626  0.317163 -0.975620  0.423664  0.871074  0.461265   
K      0.991150 -0.156517  0.449906 -0.606928  0.528167 -0.127749  0.478488   
L      0.761047 -0.990352  0.257948 -0.975536  0.593312  0.522599  0.460908   
M      0.470856 -0.579747  0.051103  0.084377  0.906042  0.232290  0.428022   
N     -0.122615 -0.025162 -0.238010 -0.164102 -0.110572  0.046628  0.033141   
P     -0.552991 -0.990519  0.034687 -0.975412 -0.241247 -0.348413  0.076876   
Q      0.371546 -0.025078  0.047388 -0.160138  0.462685  0.290440  0.262060   
R      0.695588  0.990637  0.349144  0.635851  0.293391  0.092642  0.519654   
S     -0.672513 -0.181890 -0.594038 -0.247199  0.019557 -0.116193 -0.217411   
T      0.945609 -0.405530 -0.293115 -0.243042  0.097942  0.394727  0.019238   
V     -0.268057 -0.990309  0.159775 -0.975643  0.397758  0.986957  0.227810   
W      0.144605 -0.413660  0.974184 -0.296443  0.423797  0.603931  0.994519   
Y     -0.375230 -0.201153  0.205606  0.975732 -0.084933  0.720015  0.696000   

             pI  
index            
0      0.058469  
A     -0.190182  
C     -0.421094  
D     -0.992262  
E     -0.880627  
F     -0.319135  
G     -0.197489  
H      0.204822  
I     -0.185155  
K      0.739140  
L     -0.195070  
M     -0.254631  
N     -0.336553  
P     -0.115677  
Q     -0.276944  
R      0.992312  
S     -0.269544  
T     -0.289246  
V     -0.200038  
W     -0.217299  
Y     -0.274526

In [478]:
final = final.fillna(value=0.00000000000000001)

In [479]:
def calculate_variation(data, col):
    one_column = data[[col]]
    one_column = one_column.append(pd.DataFrame([-0.999, 0.999], index = ["N_0", "N_1"], columns=[col]))
    one_column[col+"_min"] =one_column.sort_values(col).rolling(window=2).apply(lambda x: (x[0] - x[1])/2, raw=True)
    one_column[col +"_max"] =one_column.sort_values(col, ascending=False)[col].rolling(window=2).apply(lambda x: (x[0] - x[1])/2, raw=True)
    one_column = one_column.drop(["N_0", "N_1"], axis=0)
    return list(zip(one_column[col+"_min"].values.tolist(), one_column[col+"_max"].values.tolist()))
    #return one_column

In [502]:
col = "Lip"
one_column = final[[col]]
one_column = one_column.append(pd.DataFrame([-0.999, 0.999], index = ["N_0", "N_1"], columns=[col]))
one_column[col+"_min"] =one_column.sort_values(col).rolling(window=2).apply(lambda x: (x[0] - x[1])/2, raw=True)
one_column[col +"_max"] =one_column.sort_values(col, ascending=False)[col].rolling(window=2).apply(lambda x: (x[0] - x[1])/2, raw=True)
one_column = one_column.drop(["N_0", "N_1"], axis=0)
one_column

Lip   Lip_min   Lip_max
0 -0.990868 -0.004066  0.014059
A -0.754024 -0.104363  0.040756
C -0.654440 -0.009037  0.050724
D -0.168480 -0.049789  0.022932
E  0.409223 -0.018838  0.030816
F -0.391900 -0.080546  0.008335
G -0.962751 -0.014059  0.104363
H  0.111706 -0.117161  0.016449
I  0.508630 -0.018887  0.093479
K  0.991150 -0.022770  0.003925
L  0.761047 -0.032730  0.092281
M  0.470856 -0.030816  0.018887
N -0.122615 -0.022932  0.117161
P -0.552991 -0.050724  0.080546
Q  0.371546 -0.113471  0.018838
R  0.695588 -0.093479  0.032730
S -0.672513 -0.040756  0.009037
T  0.945609 -0.092281  0.022770
V -0.268057 -0.053586  0.049789
W  0.144605 -0.016449  0.113471
Y -0.375230 -0.008335  0.053586

In [480]:
final.shape

(21, 8)

In [481]:
variation = [] 
for c in final.columns:
    variation.append(calculate_variation(final, c))

In [482]:
np.array(variation).shape

(8, 21, 2)

In [483]:
np.array(variation).shape

(8, 21, 2)

In [484]:
final.sum(axis=1)

index
0   -6.837783
A   -2.754805
C   -1.685018
D   -1.209120
E    0.474343
F    0.330298
G   -4.872189
H    0.931881
I    0.430396
K    2.295657
L    0.434856
M    1.338312
N   -0.917244
P   -3.112698
Q    0.971960
R    4.569220
S   -2.279231
T    0.226582
V   -0.661747
W    2.213633
Y    1.661512
dtype: float64

In [485]:
final_values = final.values

In [486]:
final_values

array([[-0.99086824, -0.99049258, -0.97375604, -0.97549564, -0.98396655,
        -0.98695188, -0.99472098,  0.05846907],
       [-0.75402442, -0.99063972, -0.46735907, -0.9757074 ,  0.86707001,
        -0.02316806, -0.22079448, -0.19018164],
       [-0.65443964, -0.66891145, -0.63073225,  0.41422632, -0.07163595,
         0.39478968, -0.0472208 , -0.42109393],
       [-0.16847977,  0.25439652, -0.42869251,  0.17770937,  0.33254099,
        -0.35985504, -0.02447825, -0.99226157],
       [ 0.40922329,  0.25444606, -0.14109466,  0.1914134 ,  0.98437137,
        -0.55745379,  0.21406434, -0.88062661],
       [-0.39189968, -0.83053969,  0.5662761 , -0.46228827,  0.48877502,
         0.61552284,  0.6635869 , -0.31913532],
       [-0.96275087, -0.99059005, -0.91905129, -0.97530442, -0.24108448,
        -0.11609759, -0.46982169, -0.19748889],
       [ 0.11170592,  0.04927729,  0.22333138, -0.34303485,  0.31922932,
         0.02326292,  0.34328655,  0.20482222],
       [ 0.50862986, -0.9906257 

In [487]:
np.save("../data/protein/hand_crafted_embeddings_8.npy", final_values)
np.save("../data/protein/embeddings_variation_8.npy", variation)

In [495]:
variation[0][0]

(-0.004065880008005007, 0.014058685682441674)

In [496]:
variation[0][0][0] + variation[0][0][1] 

0.009992805674436667

In [500]:
abs(variation[0][0][0] - variation[0][0][1])/1.95

0.00929464907202394

In [ ]:
variation[0][0][0] + variation[0][0][1] 

In [110]:
hist, bin_edges = np.histogram(final.values)

In [111]:
hist, bin_edges

(array([26, 17,  8, 16, 16, 16, 15, 17, 10, 11], dtype=int64),
 array([-9.96547729e-01, -7.97227764e-01, -5.97907799e-01, -3.98587834e-01,
        -1.99267869e-01,  5.20963442e-05,  1.99372061e-01,  3.98692026e-01,
         5.98011991e-01,  7.97331956e-01,  9.96651921e-01]))

In [112]:
np.max(final.values)

0.99665192121883

In [113]:
np.min(final.values)

-0.996547728530466

In [41]:
import tensorflow as tf

In [42]:
tf.enable_eager_execution()

In [43]:
embeddings = tf.constant([[ 0.        ,  0.        ,  0.        ],
       [-0.78874256,  0.43069857, -0.47393251],
       [-0.68765258,  0.19845299, -0.64110991],
       [-0.19540625, -0.46831037, -0.43458175],
       [ 0.39009043, -0.46831037, -0.14043892],
       [-0.4217928 ,  0.31515591,  0.5829058 ],
       [-1.        ,  0.43069857, -0.93603945],
       [ 0.088746  , -0.32018371,  0.23223556],
       [ 0.49063027,  0.43069857,  0.32813161],
       [ 0.97943816, -0.1715736 ,  0.46384033],
       [ 0.74644982,  0.43069857,  0.26766763],
       [ 0.45239487,  0.1340585 ,  0.05631338],
       [-0.14891861, -0.26652163, -0.23952655],
       [-0.58491215,  0.43069857,  0.03943025],
       [ 0.3517175 , -0.26652163,  0.0522144 ],
       [ 0.68015679, -1.        ,  0.360837  ],
       [-0.70594505, -0.15329949, -0.60368124],
       [ 0.93336313,  0.00826686, -0.29583345],
       [-0.2963587 ,  0.43069857,  0.16728669],
       [ 0.12175498,  0.01397148,  1.        ],
       [-0.40501324, -0.13937636,  0.21428112]])

In [44]:
embeddings

<tf.Tensor: id=1, shape=(21, 3), dtype=float32, numpy=
array([[ 0.        ,  0.        ,  0.        ],
       [-0.78874254,  0.43069857, -0.4739325 ],
       [-0.6876526 ,  0.198453  , -0.6411099 ],
       [-0.19540624, -0.46831036, -0.43458176],
       [ 0.39009044, -0.46831036, -0.14043891],
       [-0.4217928 ,  0.31515592,  0.5829058 ],
       [-1.        ,  0.43069857, -0.93603945],
       [ 0.088746  , -0.32018372,  0.23223557],
       [ 0.49063027,  0.43069857,  0.32813162],
       [ 0.9794382 , -0.1715736 ,  0.46384034],
       [ 0.7464498 ,  0.43069857,  0.26766762],
       [ 0.45239487,  0.1340585 ,  0.05631338],
       [-0.14891861, -0.26652163, -0.23952655],
       [-0.5849121 ,  0.43069857,  0.03943025],
       [ 0.3517175 , -0.26652163,  0.0522144 ],
       [ 0.68015677, -1.        ,  0.360837  ],
       [-0.7059451 , -0.1532995 , -0.60368127],
       [ 0.93336314,  0.00826686, -0.29583344],
       [-0.2963587 ,  0.43069857,  0.1672867 ],
       [ 0.12175498,  0.01397148,

In [15]:
acid_embeddings = tf.get_variable("acid_embeddings", shape=[21, 3],
                                              initializer=tf.constant_initializer(final[:, :3]), trainable=False)

In [16]:
real_x = tf.nn.embedding_lookup(acid_embeddings, [0,1,2,3,4,5,6])

In [17]:
real_x

<tf.Tensor: id=12, shape=(7, 3), dtype=float32, numpy=
array([[ 0.        ,  0.        ,  0.        ],
       [-0.78874254,  0.43069857, -0.4739325 ],
       [-0.6876526 ,  0.19845298, -0.6411099 ],
       [-0.19540626, -0.46831036, -0.43458176],
       [ 0.39009044, -0.46831036, -0.14043893],
       [-0.4217928 ,  0.31515592,  0.58290577],
       [-1.        ,  0.43069857, -0.93603945]], dtype=float32)>

In [18]:
emb_distances = tf.matmul(
            tf.nn.l2_normalize(acid_embeddings, axis=1),
            tf.nn.l2_normalize(real_x, axis=1),
            transpose_b=True)


In [19]:
emb_distances

<tf.Tensor: id=29, shape=(21, 7), dtype=float32, numpy=
array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  1.        ,  0.95438176,  0.2333401 , -0.6968484 ,
         0.24079096,  0.9719342 ],
       [ 0.        ,  0.95438176,  0.99999976,  0.49855018, -0.4511665 ,
        -0.02797707,  0.9953341 ],
       [ 0.        ,  0.2333401 ,  0.49855018,  0.99999994,  0.48847306,
        -0.6068856 ,  0.41748512],
       [ 0.        , -0.6968484 , -0.4511665 ,  0.48847306,  1.        ,
        -0.80192816, -0.51257807],
       [ 0.        ,  0.24079096, -0.02797707, -0.6068856 , -0.80192816,
         1.0000001 ,  0.01055735],
       [ 0.        ,  0.9719342 ,  0.99533415,  0.41748515, -0.5125781 ,
         0.01055733,  1.0000001 ],
       [ 0.        , -0.77203405, -0.7020516 ,  0.1169682 ,  0.59929514,
        -0.00932344, -0.76286685],
       [ 0.        , -0.480889  , -0.6584349 , -0.90168554, -0.12339413,
       

In [20]:
tf.argmax(emb_distances, axis=0)

<tf.Tensor: id=32, shape=(7,), dtype=int64, numpy=array([0, 1, 2, 3, 4, 5, 6], dtype=int64)>

In [43]:
tf.nn.l2_normalize(acid_embeddings, axis=1) #[-0.78874254,  0.43069857, -0.4739325 ]

<tf.Tensor: id=155, shape=(21, 3), dtype=float32, numpy=
array([[ 0.        ,  0.        ,  0.        ],
       [-0.7763319 ,  0.42392164, -0.4664753 ],
       [-0.715656  ,  0.20653462, -0.6672179 ],
       [-0.29247993, -0.700957  , -0.6504727 ],
       [ 0.6236793 , -0.7487378 , -0.22453472],
       [-0.5369731 ,  0.40121657,  0.7420817 ],
       [-0.69645065,  0.29996032, -0.6519053 ],
       [ 0.21892463, -0.7898507 ,  0.57289433],
       [ 0.671473  ,  0.58945096,  0.44907856],
       [ 0.892657  , -0.15637167,  0.4227427 ],
       [ 0.82717836,  0.47727862,  0.29661587],
       [ 0.9520327 ,  0.2821165 ,  0.11850748],
       [-0.3837605 , -0.68682134, -0.6172555 ],
       [-0.8040621 ,  0.59206915,  0.05420365],
       [ 0.7914957 , -0.59977317,  0.1175019 ],
       [ 0.53892225, -0.79235005,  0.2859092 ],
       [-0.7498647 , -0.16283685, -0.64123863],
       [ 0.95322925,  0.00844282, -0.3021301 ],
       [-0.5398929 ,  0.78462726,  0.30475536],
       [ 0.1208508 ,  0.0138677

In [58]:
a = [[1,2,3],[50,60,70],[800, 900,1000], [-1, -2, -3]]
a = tf.expand_dims(a, axis=0)
a = tf.expand_dims(a, axis=3)

In [63]:
tf.squeeze(a)

<tf.Tensor: id=26, shape=(4, 3), dtype=int32, numpy=
array([[   1,    2,    3],
       [  50,   60,   70],
       [ 800,  900, 1000],
       [  -1,   -2,   -3]])>

In [60]:
x = tf.image.resize_nearest_neighbor(a, [4, 3 * 2])

In [62]:
tf.squeeze(x)

<tf.Tensor: id=24, shape=(4, 6), dtype=int32, numpy=
array([[   1,    1,    2,    2,    3,    3],
       [  50,   50,   60,   60,   70,   70],
       [ 800,  800,  900,  900, 1000, 1000],
       [  -1,   -1,   -2,   -2,   -3,   -3]])>