In [4]:
import pandas as pd
import numpy as np
from common.bio.constants import *

In [2]:
PATH= "C:\\Users\\Donatas\\Workspace\\Machine Learning\\SynBioAi\\PREnzyme\\data\\smiles_vec.txt"

In [45]:
column_list = [str(i) for i in range(101)]

In [46]:
smiles_vec = pd.read_csv(PATH, sep=" ", header=None, index_col=0, names=column_list)

In [51]:
smiles_vec["9"]

0
c   -0.109788
C   -0.197438
)   -0.163131
(   -0.172670
O   -0.109462
=   -0.117166
N   -0.054432
1   -0.073978
2   -0.006089
@   -0.172673
3   -0.265881
]    0.051921
[   -0.019285
n   -0.015459
H   -0.196171
4   -0.049803
5   -0.076869
F    0.099045
S   -0.011607
\   -0.247578
l   -0.174371
6   -0.171863
s   -0.042817
o   -0.023751
+    0.206644
-    0.291304
/   -0.493658
.   -0.061962
#   -0.130679
B   -0.388466
7   -0.141008
r   -0.262082
%   -0.218616
8   -0.139841
P   -0.010746
9   -0.299744
0   -0.215340
I    0.201309
a    0.439959
i   -0.448071
e   -0.305326
K    0.179916
L   -0.451476
p   -0.456420
A    0.095847
Z   -0.100418
g   -0.060233
T   -0.117200
M   -0.002320
t    0.640149
b   -0.019089
R   -0.017561
u    0.265576
V    0.527728
X   -0.076679
d    0.162760
G    0.179120
_    0.399280
m    0.437441
Name: 9, dtype: float64

PCA

In [80]:
from sklearn.decomposition import PCA

pca = PCA(n_components=8)

principalComponents = pca.fit_transform(smiles_vec)
data = pd.DataFrame(data = principalComponents)

In [81]:
data.head()

0         1         2         3         4         5         6  \
0 -1.016257 -0.045653  0.076941  0.131717 -0.519489 -0.149488 -0.043070   
1 -0.859336  0.014011  0.003119 -0.079952 -0.417324 -0.022324 -0.376630   
2 -0.841043 -0.016845 -0.020365 -0.047271 -0.428503 -0.022639 -0.319339   
3 -0.873638 -0.063648 -0.019231 -0.080104 -0.402901 -0.106291 -0.270694   
4 -0.801222 -0.177214 -0.088867 -0.075941 -0.253550 -0.081680 -0.323696   

          7  
0  0.323767  
1 -0.323091  
2 -0.185662  
3 -0.203797  
4 -0.243066

In [82]:
data = (data.subtract(data.mean(axis=0), axis=1).div(data.std(ddof=0, axis=0), axis=1))
data = data.div(data.abs().max(axis=0), axis=1)

In [83]:
data.head()

0         1         2         3         4         5         6  \
0 -0.139973 -0.012167  0.023045  0.039832 -0.197059 -0.059180 -0.021347   
1 -0.118360  0.003734  0.000934 -0.024178 -0.158305 -0.008838 -0.186666   
2 -0.115840 -0.004489 -0.006100 -0.014295 -0.162545 -0.008962 -0.158272   
3 -0.120329 -0.016963 -0.005760 -0.024224 -0.152833 -0.042079 -0.134162   
4 -0.110355 -0.047229 -0.026617 -0.022965 -0.096180 -0.032336 -0.160431   

          7  
0  0.217086  
1 -0.216632  
2 -0.124486  
3 -0.136645  
4 -0.162976

In [131]:
indexed_data = pd.concat([smiles_vec.reset_index()["0"], data], axis =1, ignore_index=True).rename(columns={0: 'smiles'}).set_index('smiles')

In [132]:
transposed = indexed_data.transpose()
transposed[' '] = 0.0000000001
indexed_data = transposed.transpose()

In [133]:
smiles_dict = pd.DataFrame.from_dict(SMILES_CHARACTER_TO_ID, orient='index')

In [134]:
merged_data = pd.merge(right=indexed_data, left=smiles_dict, how="inner",left_index=True, right_index=True)

In [135]:
final = merged_data.values

In [136]:
# pd.set_option('display.float_format', lambda x: '%.5f' % x)
# data.rename(columns=AMINO_ACID_TO_ID).transpose().sort_index()

In [137]:
merged_data

0             1             2             3             4             5  \
    0  1.000000e-10  1.000000e-10  1.000000e-10  1.000000e-10  1.000000e-10   
(   1 -1.203295e-01 -1.696253e-02 -5.759914e-03 -2.422406e-02 -1.528334e-01   
)   2 -1.158400e-01 -4.489372e-03 -6.099627e-03 -1.429519e-02 -1.625450e-01   
+   4 -1.473851e-01 -5.226413e-02 -5.791226e-02 -7.851424e-03  2.937800e-01   
-   5 -1.464201e-01 -5.350854e-02 -8.825254e-02 -3.447846e-02  3.902929e-01   
1   6 -1.112232e-01  7.508538e-03  5.013178e-02  2.227703e-02 -9.795175e-02   
2   7 -1.439806e-01 -4.006252e-02  5.355979e-02  2.965180e-02 -1.784450e-01   
3   8 -1.493098e-01 -8.198163e-03  4.685109e-02  3.137591e-02 -1.992371e-01   
4   9 -1.518324e-01 -1.016283e-02  2.222479e-02  7.643236e-02 -2.195939e-01   
5  10 -1.372692e-01 -8.261809e-03  4.778317e-02  2.106100e-02 -2.011346e-01   
=  11 -1.075296e-01  6.542557e-03 -1.161549e-02 -6.512158e-03 -1.311615e-01   
C  12 -1.183596e-01  3.734108e-03  9.343178e-04 -2.417826e-02 -1.583045e-01   
H  13 -1.157649e-01 -3.174992e-02 -6.876539e-03 -5.441187e-02 -1.386898e-01   
N  14 -1.160896e-01 -1.348074e-03  3.914946e-02  2.417860e-03 -1.522331e-01   
O  15 -1.103553e-01 -4.722854e-02 -2.661671e-02 -2.296512e-02 -9.617986e-02   
P  16 -9.570817e-02  1.633729e-02 -6.409915e-02 -1.954409e-01  1.590383e-01   
S  17 -1.366674e-01 -8.371111e-02 -2.023402e-02  3.241910e-02 -1.043727e-01   
[  18 -1.147669e-01 -3.966896e-02 -5.006370e-02 -5.524497e-02 -6.623468e-02   
]  19 -1.106211e-01 -4.687278e-02 -4.184027e-02 -6.362933e-02 -5.198242e-02   
c  20  1.000000e-10  1.000000e-10  1.000000e-10  1.000000e-10  1.000000e-10   
n  21 -1.543939e-01 -2.665919e-02  9.699735e-02  3.343300e-02 -2.141424e-01   
o  22 -2.332324e-01 -1.591950e-02  1.133835e-01 -1.997273e-02 -1.433502e-01   

              6             7             8  
   1.000000e-10  1.000000e-10  1.000000e-10  
( -4.207891e-02 -1.341617e-01 -1.366455e-01  
) -8.962378e-03 -1.582716e-01 -1.244860e-01  
+ -6.526708e-02  3.706795e-01  2.746403e-01  
- -4.836104e-02  2.383984e-01  1.918358e-01  
1 -8.664867e-02 -5.271173e-02  1.223242e-01  
2 -8.235224e-02 -5.699433e-03  1.605800e-01  
3 -8.228979e-02  6.951473e-03  1.079905e-01  
4 -2.943900e-02 -1.949903e-02  5.676983e-02  
5 -1.014699e-02 -4.017441e-02 -5.872167e-02  
= -3.782961e-03 -1.775720e-01 -8.358400e-02  
C -8.837550e-03 -1.866660e-01 -2.166323e-01  
H -2.072170e-03 -2.557688e-01 -4.316946e-01  
N -1.047639e-02 -1.612501e-01 -1.251424e-01  
O -3.233566e-02 -1.604310e-01 -1.629759e-01  
P  1.738297e-01 -1.585757e-01 -1.835152e-01  
S -2.724532e-02 -5.390800e-02  8.196994e-02  
[ -2.165239e-02 -1.526100e-01 -4.091674e-01  
] -1.462530e-02 -1.658654e-01 -3.756821e-01  
c  1.000000e-10  1.000000e-10  1.000000e-10  
n -6.377176e-02  6.840557e-02  1.461266e-01  
o -8.783964e-02  1.707842e-01  4.157776e-01

In [138]:
final[0]

array([0.e+00, 1.e-10, 1.e-10, 1.e-10, 1.e-10, 1.e-10, 1.e-10, 1.e-10,
       1.e-10])

In [139]:
np.save("../data/protein/smiles_vec_8.npy", final)

In [41]:
import tensorflow as tf

In [42]:
tf.enable_eager_execution()

In [43]:
embeddings = tf.constant([[ 0.        ,  0.        ,  0.        ],
       [-0.78874256,  0.43069857, -0.47393251],
       [-0.68765258,  0.19845299, -0.64110991],
       [-0.19540625, -0.46831037, -0.43458175],
       [ 0.39009043, -0.46831037, -0.14043892],
       [-0.4217928 ,  0.31515591,  0.5829058 ],
       [-1.        ,  0.43069857, -0.93603945],
       [ 0.088746  , -0.32018371,  0.23223556],
       [ 0.49063027,  0.43069857,  0.32813161],
       [ 0.97943816, -0.1715736 ,  0.46384033],
       [ 0.74644982,  0.43069857,  0.26766763],
       [ 0.45239487,  0.1340585 ,  0.05631338],
       [-0.14891861, -0.26652163, -0.23952655],
       [-0.58491215,  0.43069857,  0.03943025],
       [ 0.3517175 , -0.26652163,  0.0522144 ],
       [ 0.68015679, -1.        ,  0.360837  ],
       [-0.70594505, -0.15329949, -0.60368124],
       [ 0.93336313,  0.00826686, -0.29583345],
       [-0.2963587 ,  0.43069857,  0.16728669],
       [ 0.12175498,  0.01397148,  1.        ],
       [-0.40501324, -0.13937636,  0.21428112]])

In [44]:
embeddings

<tf.Tensor: id=1, shape=(21, 3), dtype=float32, numpy=
array([[ 0.        ,  0.        ,  0.        ],
       [-0.78874254,  0.43069857, -0.4739325 ],
       [-0.6876526 ,  0.198453  , -0.6411099 ],
       [-0.19540624, -0.46831036, -0.43458176],
       [ 0.39009044, -0.46831036, -0.14043891],
       [-0.4217928 ,  0.31515592,  0.5829058 ],
       [-1.        ,  0.43069857, -0.93603945],
       [ 0.088746  , -0.32018372,  0.23223557],
       [ 0.49063027,  0.43069857,  0.32813162],
       [ 0.9794382 , -0.1715736 ,  0.46384034],
       [ 0.7464498 ,  0.43069857,  0.26766762],
       [ 0.45239487,  0.1340585 ,  0.05631338],
       [-0.14891861, -0.26652163, -0.23952655],
       [-0.5849121 ,  0.43069857,  0.03943025],
       [ 0.3517175 , -0.26652163,  0.0522144 ],
       [ 0.68015677, -1.        ,  0.360837  ],
       [-0.7059451 , -0.1532995 , -0.60368127],
       [ 0.93336314,  0.00826686, -0.29583344],
       [-0.2963587 ,  0.43069857,  0.1672867 ],
       [ 0.12175498,  0.01397148,

In [15]:
acid_embeddings = tf.get_variable("acid_embeddings", shape=[21, 3],
                                              initializer=tf.constant_initializer(final[:, :3]), trainable=False)

In [16]:
real_x = tf.nn.embedding_lookup(acid_embeddings, [0,1,2,3,4,5,6])

In [17]:
real_x

<tf.Tensor: id=12, shape=(7, 3), dtype=float32, numpy=
array([[ 0.        ,  0.        ,  0.        ],
       [-0.78874254,  0.43069857, -0.4739325 ],
       [-0.6876526 ,  0.19845298, -0.6411099 ],
       [-0.19540626, -0.46831036, -0.43458176],
       [ 0.39009044, -0.46831036, -0.14043893],
       [-0.4217928 ,  0.31515592,  0.58290577],
       [-1.        ,  0.43069857, -0.93603945]], dtype=float32)>

In [18]:
emb_distances = tf.matmul(
            tf.nn.l2_normalize(acid_embeddings, axis=1),
            tf.nn.l2_normalize(real_x, axis=1),
            transpose_b=True)


In [19]:
emb_distances

<tf.Tensor: id=29, shape=(21, 7), dtype=float32, numpy=
array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  1.        ,  0.95438176,  0.2333401 , -0.6968484 ,
         0.24079096,  0.9719342 ],
       [ 0.        ,  0.95438176,  0.99999976,  0.49855018, -0.4511665 ,
        -0.02797707,  0.9953341 ],
       [ 0.        ,  0.2333401 ,  0.49855018,  0.99999994,  0.48847306,
        -0.6068856 ,  0.41748512],
       [ 0.        , -0.6968484 , -0.4511665 ,  0.48847306,  1.        ,
        -0.80192816, -0.51257807],
       [ 0.        ,  0.24079096, -0.02797707, -0.6068856 , -0.80192816,
         1.0000001 ,  0.01055735],
       [ 0.        ,  0.9719342 ,  0.99533415,  0.41748515, -0.5125781 ,
         0.01055733,  1.0000001 ],
       [ 0.        , -0.77203405, -0.7020516 ,  0.1169682 ,  0.59929514,
        -0.00932344, -0.76286685],
       [ 0.        , -0.480889  , -0.6584349 , -0.90168554, -0.12339413,
       

In [20]:
tf.argmax(emb_distances, axis=0)

<tf.Tensor: id=32, shape=(7,), dtype=int64, numpy=array([0, 1, 2, 3, 4, 5, 6], dtype=int64)>

In [43]:
tf.nn.l2_normalize(acid_embeddings, axis=1) #[-0.78874254,  0.43069857, -0.4739325 ]

<tf.Tensor: id=155, shape=(21, 3), dtype=float32, numpy=
array([[ 0.        ,  0.        ,  0.        ],
       [-0.7763319 ,  0.42392164, -0.4664753 ],
       [-0.715656  ,  0.20653462, -0.6672179 ],
       [-0.29247993, -0.700957  , -0.6504727 ],
       [ 0.6236793 , -0.7487378 , -0.22453472],
       [-0.5369731 ,  0.40121657,  0.7420817 ],
       [-0.69645065,  0.29996032, -0.6519053 ],
       [ 0.21892463, -0.7898507 ,  0.57289433],
       [ 0.671473  ,  0.58945096,  0.44907856],
       [ 0.892657  , -0.15637167,  0.4227427 ],
       [ 0.82717836,  0.47727862,  0.29661587],
       [ 0.9520327 ,  0.2821165 ,  0.11850748],
       [-0.3837605 , -0.68682134, -0.6172555 ],
       [-0.8040621 ,  0.59206915,  0.05420365],
       [ 0.7914957 , -0.59977317,  0.1175019 ],
       [ 0.53892225, -0.79235005,  0.2859092 ],
       [-0.7498647 , -0.16283685, -0.64123863],
       [ 0.95322925,  0.00844282, -0.3021301 ],
       [-0.5398929 ,  0.78462726,  0.30475536],
       [ 0.1208508 ,  0.0138677

In [58]:
a = [[1,2,3],[50,60,70],[800, 900,1000], [-1, -2, -3]]
a = tf.expand_dims(a, axis=0)
a = tf.expand_dims(a, axis=3)

In [63]:
tf.squeeze(a)

<tf.Tensor: id=26, shape=(4, 3), dtype=int32, numpy=
array([[   1,    2,    3],
       [  50,   60,   70],
       [ 800,  900, 1000],
       [  -1,   -2,   -3]])>

In [60]:
x = tf.image.resize_nearest_neighbor(a, [4, 3 * 2])

In [62]:
tf.squeeze(x)

<tf.Tensor: id=24, shape=(4, 6), dtype=int32, numpy=
array([[   1,    1,    2,    2,    3,    3],
       [  50,   50,   60,   60,   70,   70],
       [ 800,  800,  900,  900, 1000, 1000],
       [  -1,   -1,   -2,   -2,   -3,   -3]])>